general {
    lock_cmd = pidof hyprlock || hyprlock       # don't spawn multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # wake screen after resume
    ignore_dbus_inhibit = false
}

# 29 min — dim screen (warning before lock)
listener {
    timeout = 1740
    on-timeout = hyprctl keyword decoration:active_opacity 0.5 && hyprctl keyword decoration:inactive_opacity 0.4
    on-resume  = hyprctl keyword decoration:active_opacity 0.82 && hyprctl keyword decoration:inactive_opacity 0.70
}

# 30 min — lock screen
listener {
    timeout = 1800
    on-timeout = loginctl lock-session
    on-resume  = hyprctl keyword decoration:active_opacity 0.82 && hyprctl keyword decoration:inactive_opacity 0.70
}

# 31 min — screen off
listener {
    timeout = 1860
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
}
