preload = @WALLPAPER@
preload = @WALLPAPER@
preload = @WALLPAPER@
preload = @WALLPAPER@
preload = @WALLPAPER@
preload = @WALLPAPER@
preload = @WALLPAPER@
preload = @WALLPAPER@
preload = @WALLPAPER@
preload = @WALLPAPER@
preload = @WALLPAPER@

wallpaper = @MONITOR_2@,@WALLPAPER@
wallpaper = @MONITOR_1@,@WALLPAPER@
splash = false
