#!/usr/bin/env bash
# Checks run inside a fresh install (by install-in-container.sh, or by hand).
set -u
P="$HOME/.local/share/prime-linux"; L="$P/layer"; fail=0
S="${XDG_STATE_HOME:-$HOME/.local/state}/prime"
ck() { if ( eval "$2" ) >/dev/null 2>&1; then echo "  PASS  $1"; else echo "  FAIL  $1"; fail=$((fail+1)); fi; }

echo "-- the install itself"
ck "installed copy exists"                 "[ -x $L/bin/prime-menu ]"
ck "hyprland.conf seeded and sources Prime" "grep -q prime-linux ~/.config/hypr/hyprland.conf"
ck "hardware/monitors/addons/keyboard files exist" "[ -f ~/.config/hypr/hardware.conf ] && [ -f ~/.config/hypr/monitors.conf ] && [ -f ~/.config/hypr/addons.conf ] && [ -f ~/.config/hypr/keyboard.conf ]"
ck "keyboard.conf has a layout"             "grep -qE 'kb_layout = [a-z]+' ~/.config/hypr/keyboard.conf"
ck "theme files generated"                  "[ -f ~/.config/prime/theme/colors.css ] && [ -f ~/.config/prime/theme/hyprland.conf ] && [ -f ~/.config/prime/theme/hyprpaper.conf ]"
ck "text sizes generated from one setting"  "grep -q prime-font-body ~/.config/prime/theme/fonts.rasi && grep -q prime_font_clock ~/.config/prime/theme/hyprlock.conf"
ck "emblem generated in the accent"         "grep -q f87171 ~/.config/prime/theme/mark.svg && [ -s ~/.config/prime/theme/mark.png ]"
ck "app-list entries installed, paths filled" "[ -f ~/.local/share/applications/prime-menu.desktop ] && ! grep -q @LAYER@ ~/.local/share/applications/prime-*.desktop"
ck "install log written"                    "ls $S/logs/install-*.log"
ck "install marked complete"                "grep -qx complete $S/install.progress"
ck "manifest records what changed"          "grep -q '^created ' $S/install.manifest && grep -q '^gsetting ' $S/install.manifest"
# only when the harness planted a config of "yours" before installing (install-in-container does)
if [ -n "${PRIME_TEST_PLANTED_CONFIG:-}" ]; then
ck "existing config backed up and recorded" "grep -q '^replaced .*kitty/kitty.conf' $S/install.manifest && grep -q 'before-prime' \$(sed -n 's/^BACKUP=//p' ~/.config/prime/install.conf)/kitty/kitty.conf"
fi
ck "all of Prime's packages present"        "[ -z \"\$($L/bin/prime-missing-packages)\" ]"
ck "re-run is a no-op that stays complete"  "bash $P/install.sh --no-packages --yes && grep -qx complete $S/install.progress"
ck "dry run changes nothing"                "h=\$(mktemp -d) && HOME=\$h XDG_STATE_HOME= bash $P/install.sh --dry-run --no-packages && [ -z \"\$(ls -A \$h)\" ]"

echo "-- the desktop config"
ck "Hyprland accepts the whole config"      "Hyprland --verify-config -c ~/.config/hypr/hyprland.conf"
ck "every bind has a description"           "! grep -hE '^bind[a-z]* =' $L/default/hypr/*.conf $L/addons/*/hypr.conf | grep -vE '^bind[a-z]*d[a-z]* ='"
ck "no key is bound twice"                  "[ -z \"\$(grep -hE '^bind[a-z]* =' $L/default/hypr/*.conf | cut -d, -f1,2 | sed 's/^[^=]*= *//; s/ *, */,/' | sort | uniq -d)\" ]"
ck "new binds: record, colour, emoji, switches" "for k in prime-record prime-colour prime-emoji 'prime-toggle nightlight' 'prime-toggle idle' 'prime-toggle dnd' 'prime-keyboard next' 'prime-osd volume up'; do grep -q \"\$k\" $L/default/hypr/bindings.conf || exit 1; done"
ck "top bar config builds"                  "$L/bin/prime-bar --print top | jq -e '.\"modules-right\" | length > 5'"
ck "bar has battery, recording, switches, keyboard" "$L/bin/prime-bar --print top | jq -e '(.\"group/status\".modules | index(\"battery\")) and (.\"modules-right\" | index(\"custom/recording\") and index(\"custom/toggles\") and index(\"custom/keyboard\"))'"
ck "bar logo path expanded"                 "$L/bin/prime-bar --print top | jq -e '.\"image#logo\".path | startswith(\"/\")'"
ck "side bar config builds"                 "$L/bin/prime-bar --print side | jq -e '.\"modules-left\" | length > 0'"
ck "menu: every row resolves"               "$L/bin/prime-menu --check | tail -1 | grep -q 'every row resolves'"
ck "menu has Quick switches + Capture & tools" "$L/bin/prime-menu --list | grep -q '^toggles' && $L/bin/prime-menu --list | grep -q '^tools'"
ck "every bar click target exists"          "$L/bin/prime-bar --print top | jq -r '.[] | objects | .[\"on-click\"] // empty' | sed 's#^~#'\$HOME'#' | awk '{print \$1}' | sort -u | while read -r c; do command -v \"\$c\" || [ -x \"\$c\" ] || exit 1; done"
ck "right-click menus list items"           "$L/bin/prime-context bar.audio --list | grep -q 'Sound settings'"
ck "right-click: battery/recording/switches/keyboard" "for e in bar.battery bar.recording bar.toggles bar.keyboard; do $L/bin/prime-context \$e --list | grep -qv 'Copy this value' || exit 1; done"
ck "spotlight self-test"                    "python3 $L/bin/prime-spotlight --query notes"
ck "start menu installed and self-tests"    "[ -x $L/bin/prime-start ] && python3 $L/bin/prime-start --selftest"
ck "the P logo opens the start menu"        "python3 $L/bin/prime-bar --print top | jq -e '.\"image#logo\".\"on-click\" | endswith(\"prime-start\")'"

echo "-- the new tools (headless)"
ck "bar widgets are silent when idle"       "[ \"\$($L/bin/prime-record status)\" = '{\"text\":\"\"}' ] && $L/bin/prime-keyboard status | jq -e '.text == \"\"'"
ck "keyboard: two layouts show on the bar"  "cp ~/.config/hypr/keyboard.conf /tmp/kb && sed -i 's/kb_layout = .*/kb_layout = us,de/' ~/.config/hypr/keyboard.conf && $L/bin/prime-keyboard status | jq -e '.text | test(\"us\")' ; r=\$?; cp /tmp/kb ~/.config/hypr/keyboard.conf; exit \$r"
ck "switch status answers"                  "$L/bin/prime-toggle status | jq -e 'has(\"text\")' && $L/bin/prime-toggle status nightlight | grep -qE '^(on|off)$'"
ck "web app: install, list, remove"         "$L/bin/prime-webapp install 'Test Site' example.com && grep -q 'prime-webapp open https://example.com' ~/.local/share/applications/prime-webapp-test-site.desktop && $L/bin/prime-webapp list | grep -q '^Test Site' && $L/bin/prime-webapp remove 'Test Site' && [ ! -e ~/.local/share/applications/prime-webapp-test-site.desktop ]"
ck "web app: refuses non-web addresses"     "! $L/bin/prime-webapp install Bad 'javascript:alert(1)' && ! $L/bin/prime-webapp install 'a/b' example.com"
ck "battery alert exits quietly on a desktop" "timeout 5 $L/bin/prime-battery-alert --once"
ck "OSD helpers parse"                      "for f in prime-titlebars prime-osd prime-toggle prime-record prime-wifi prime-bluetooth prime-sound prime-keyboard prime-power-profile prime-colour prime-emoji prime-webapp prime-migrate; do bash -n $L/bin/\$f || exit 1; done"
ck "new services linked"                    "[ -L ~/.config/systemd/user/prime-osd.service ] && [ -L ~/.config/systemd/user/prime-battery-alert.service ]"

echo "-- migrations"
ck "fresh install has no pending migrations" "$L/bin/prime-migrate --pending"
ck "old install: keyboard migration runs once" "cp ~/.config/hypr/hyprland.conf /tmp/h && sed -i '/keyboard.conf/d' ~/.config/hypr/hyprland.conf && sed -i '/^1790862549.sh$/d' ~/.config/prime/migrations && ! $L/bin/prime-migrate --pending && $L/bin/prime-migrate && [ \$(grep -c 'hypr/keyboard.conf' ~/.config/hypr/hyprland.conf) = 1 ] && $L/bin/prime-migrate && [ \$(grep -c 'hypr/keyboard.conf' ~/.config/hypr/hyprland.conf) = 1 ] && $L/bin/prime-migrate --pending"
ck "config still valid after migration"     "Hyprland --verify-config -c ~/.config/hypr/hyprland.conf"
ck "a failing migration stops the run"      "d=\$(mktemp -d) && printf '#!/bin/bash\n# fails\nexit 3\n' > \$d/100.sh && printf '#!/bin/bash\n# after\ntrue\n' > \$d/200.sh && ! PRIME_MIGRATIONS_DIR=\$d $L/bin/prime-migrate && PRIME_MIGRATIONS_DIR=\$d $L/bin/prime-migrate --pending | grep -q 200.sh"

echo "-- system pieces and add-ons"
ck "services linked"                        "[ -L ~/.config/systemd/user/prime-bar@.service ]"
ck "commands on PATH dir"                   "[ -L ~/.local/bin/prime-update ] && [ -L ~/.local/bin/prime-migrate ]"
ck "pacman backup hook installed"           "[ -f /etc/pacman.d/hooks/zz-prime-desktop-backup.hook ]"
ck "a login screen is enabled"              "[ -L /etc/systemd/system/display-manager.service ]"
ck "the login screen offers Prime"          "cmp $L/system/wayland-sessions/prime.desktop /usr/share/wayland-sessions/prime.desktop"
ck "desktop backup works"                   "$L/bin/prime-desktop-backup save test && ls ~/.config-backups/desktop/*_test.tar.gz"
ck "accent switch rewrites colours"         "$L/bin/prime-theme --set-accent 60a5fa && grep -q 60a5fa ~/.config/prime/theme/colors.css"
ck "add-on enable (no setup) + bar merge"   "echo ai >> ~/.config/prime/addons && $L/bin/prime-addon --relink && grep -q addons/ai ~/.config/hypr/addons.conf && $L/bin/prime-bar --print top | jq -e '.\"modules-left\" | index(\"custom/ask\")'"
ck "config still valid with add-on"        "Hyprland --verify-config -c ~/.config/hypr/hyprland.conf"
ck "right-click gets Ask rows with add-on"  "$L/bin/prime-context bar.cpu --list | grep -q 'Ask Prime'"
ck "menu rows still resolve with the AI add-on"  "$L/bin/prime-menu --check | tail -1 | grep -q 'every row resolves'"
ck "welcome app loads (GTK 4 + libadwaita)"     "python3 -c 'import gi; gi.require_version(\"Gtk\",\"4.0\"); gi.require_version(\"Adw\",\"1\"); from gi.repository import Adw' && python3 -c 'import ast,sys; ast.parse(open(sys.argv[1]).read())' $L/bin/prime-welcome"
ck "assistant: toolbox, permissions, mock model, welcome" "bash $L/addons/ai/tests/run.sh"
ck "Prime window self-test (headless part)"  "python3 $L/bin/prime-panel --selftest"
ck "health check reports in the window's words" "PRIME_PANEL=1 $L/bin/prime-doctor | grep -q '^@summary '"
ck "every bar item reachable by keyboard"    "[ \$($L/bin/prime-bar --keys --list | wc -l) -ge 15 ]"
ck "static suite on the installed copy"     "python3 $P/tests/check-static.py"
ck "personal add-ons load in every tool"     "bash $P/tests/check-personal-addons.sh"
ck "prime-import: dry run, apply, verify, undo" "bash $P/tests/check-import.sh"
ck "no trace of the author's machine"      "! grep -rIl -e /home/sean -e '\\bsean\\b' $L ~/.config/hypr ~/.config/kitty ~/.config/prime"
echo; [ $fail = 0 ] && echo "ALL PASSED" || echo "$fail FAILED"; exit $fail
